### PR TITLE
Blog App: validations and model specs

### PR DESCRIPTION
**Pull request by Ibnballo1**
I implemented the following in this PR:

- Add the following validations:
    - For the User model:
        - Name must not be blank.
        - PostsCounter must be an integer greater than or equal to zero.
    - For the Post model:
        - Title must not be blank.
        - Title must not exceed 250 characters.
        - CommentsCounter must be an integer greater than or equal to zero.
        - LikesCounter must be an integer greater than or equal to zero.
- Add unit specs for all of your models' methods and validations.

### CODE REVIEW

**Review by Lucas-Masaba — CHANGES_REQUESTED** [review]
# Hello @Ibnballo1  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

almost-there

## Highlights 🍾 
- Linter checks passing ✔️ 
- Descriptive pull request 📜 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] I cannot run migrations with `rails db:migrate` because of this error in the image below. If you delete your database, create it and migrate it again with this command `rails db:drop db:create db:migrate`, you will see the error message. Every time a new reviewer looks through your project, it is created and migrated. And so, your migrations should be able to work to create the schema.
image
This is because you are adding foreign keys before the tables are actually created 
image
You can fix this by adding the foreign keys after the tables have been created with the `rails g migration` command

**Comment by Ibnballo1** [comment]
> * rails db:drop db:create db:migrate

Thanks @Lucas-Masaba  but it is actually working on my system
image

**Comment by Lucas-Masaba** [comment]
Hello @Ibnballo1 , I'm glad we resolved this over our slack huddle. Happy Coding 👨‍💻

**Review by rotimiazeez — APPROVED** [review]
Hi @Ibnballo1 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- All tests are passing ✔️
- Good communication with the CR 👏🏽
- No linter error ✔️
- Descriptive READMEand PR ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
